auto_goal_publisher:
  ros__parameters:
    # 토픽/프레임
    costmap_topic: "/local_costmap/costmap"
    camera_frame: "camera_link"

    # 반경: 명령용/추정용
    radius: 3.3
    estimation_radius: 2.0

    # 복도 폭
    sidewalk_width: 2.26

    # 샘플 수
    angle_samples: 160

    # 코스트맵 해석
    occ_threshold: 80
    unknown_is_obstacle: true

    # goal 전송 정책
    force_streaming: true
    min_goal_interval_sec: 0.3
    disable_hysteresis: false
    force_send_on_failure: true

    # 히스테리시스 파라미터
    goal_sep_distance: 0.30
    goal_sep_yaw_deg: 10.0

    # yaw 정책
    lock_yaw_to_robot: true
    yaw_realign_deg: 30.0
    keep_goal_yaw_stable: true

    # 안정화 파라미터
    pair_cluster_tol: 0.18
    mid_angle_ema: 0.12
    max_goal_angle_step_deg: 5.0

    # 안전 레이어
    los_check: true
    los_samples: 40
    los_free_ratio: 0.60
    radius_fallback_scales: [0.75, 0.5]

    # 엣지 판정
    contact_min_neighbors: 3

    # TF / QoS / 마커
    tf_use_latest: true
    qos_reliable: true
    marker_lifetime_sec: 0.5
